#!/bin/bash
# Installs the Tusky ops config on the VM. Idempotent. Run from ~/CHHBot as ubuntu:
#   sudo bash ops/install.sh
set -euo pipefail
cd "$(dirname "$0")"

# 2G swap so memory pressure degrades gracefully instead of stalling I/O
if [ ! -f /swapfile ]; then
  fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi
echo 'vm.swappiness=10' > /etc/sysctl.d/99-tusky-swap.conf && sysctl -q -p /etc/sysctl.d/99-tusky-swap.conf

# PM2 under systemd: pm2-ubuntu.service is generated by `pm2 startup`; this override hardens it
mkdir -p /etc/systemd/system/pm2-ubuntu.service.d
install -m 644 pm2-ubuntu.override.conf /etc/systemd/system/pm2-ubuntu.service.d/override.conf

# External watchdog every 5 min
install -m 755 tusky-watchdog.sh /usr/local/bin/tusky-watchdog.sh
install -m 644 tusky-watchdog.service tusky-watchdog.timer /etc/systemd/system/

systemctl daemon-reload
systemctl enable pm2-ubuntu tusky-watchdog.timer
systemctl restart pm2-ubuntu
systemctl start tusky-watchdog.timer
echo "done: $(systemctl is-active pm2-ubuntu) / timer $(systemctl is-active tusky-watchdog.timer)"
